vich_uploader:
    db_driver: orm

    mappings:
        speaker_avatar:
            uri_prefix: /avatars/speakers
            upload_destination: '%kernel.project_dir%/public/avatars/speakers'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
